export const navigation = {
  home: "/",
  primary: [{ label: "Product", href: "/product" }, { label: "Research", href: "/research" }],
  account: [{ label: "Log In", href: "/login" }, { label: "Sign Up For Free", href: "/signup" }],
};

export const pageConfig = {
  nextSectionViewports: 5,
} as const;

export const globeConfig = {
  diameterViewportHeight: 0.75,
  sidePadding: 32,
  centerY: 0.46,
  orientation: { longitude: -35, latitude: 12 },
  sampleSpacingDegrees: 2.5,
  silhouetteSpacingDegrees: 2.9,
  dotStride: 2,
  northernCluster: { minY: 0.58, minX: -0.8, maxX: -0.1, minSpacing: 0.055 },
  coreSize: 7,
  coreOpacity: 0.92,
  haloScale: 3.4,
  haloOpacity: 0.18,
  haloTint: "#88DCE8",
  hoverAmplitude: [3, 5],
  periodSeconds: [4, 7],
  durationSeconds: 4.6,
  loop: true,
  flight: {
    focus: { latitude: 40.7128, longitude: -74.0060 },
    scrollViewports: 4,
    postFlightViewports: 1.5,
    finalCoreSize: 220,
    mobileFinalCoreSize: 160,
    finalHaloScale: 1.8,
    completionZone: { start: 0.48, end: 0.56 },
    revealProgress: 0.9,
    minimumHoldMs: 1400,
    hoverFadeEnd: 0.08,
    smoothing: { responseSeconds: 0.12, settleSeconds: 0.34, inputBlendSeconds: 0.16, epsilon: 0.00008 },
    exitMargin: 24,
    crossfadeStart: 0.15,
    crossfadeEnd: 0.8,
  },
  network: {
    desktopLiftViewportHeight: 0.03,
    mobileFocusViewportHeight: 0.27,
    mobileFocusMaxFromHeader: 130,
    mobileHeaderGap: 14,
    mobileBottomReserve: 88,
    mobileMaxSpan: 400,
  },
  dprCap: 1.5,
  mobile: {
    breakpoint: 820,
    diameterViewportHeight: 0.66,
    sidePadding: 16,
    centerY: 0.5,
    initialTopOffset: 396,
    initialLiftViewportHeight: 0.02,
    heroGap: 24,
    coreSize: 4.2,
    hoverAmplitude: [1.5, 2.5],
  },
} as const;
